# Generated by Django 5.2 on 2025-04-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0002_alter_product_options_alter_product_active_and_more'),
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
