# Generated by Django 5.2 on 2025-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_product_categories'),
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='eshop_products_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
