# Generated by Django 5.2 on 2025-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0006_alter_productgallery_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': ' تصاویر'},
        ),
    ]
