# Generated by Django 5.2 on 2025-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_product_categories'),
        ('eshop_tag', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tags', to='eshop_product.product', verbose_name='محصولات'),
        ),
    ]
