# Generated by Django 5.2 on 2025-05-13 10:37

import eshop_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_persian', models.CharField(max_length=255, verbose_name='نام سایت به فارسی ')),
                ('site_name_english', models.CharField(max_length=200, verbose_name='نام سایت به انگلیسی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_to_logo, verbose_name='لوگو')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=20, verbose_name='موبایل')),
                ('fax', models.CharField(max_length=20, verbose_name='فکس')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('copy_right', models.CharField(max_length=300, verbose_name='کپی رایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'همه ی قسمت های تنظیمات',
            },
        ),
    ]
