# Generated by Django 5.2 on 2025-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_alter_sitesetting_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='درباره ما'),
        ),
    ]
