# Generated by Django 5.2 on 2025-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت محصول'),
        ),
    ]
