# Generated by Django 5.2 on 2025-05-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0002_alter_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
